# Generated by Django 6.0.6 on 2026-07-20 14:11

import accounts.tokens
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
        ('nannies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('split_method', models.CharField(choices=[('equal', 'Equally between the families present'), ('by_children', 'In proportion to the children present')], default='equal', max_length=20)),
                ('paid_leave_days', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='nannies.nanny')),
            ],
            options={
                'ordering': ['-starting_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_children', to='children.child')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_children', to='contracts.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='children',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractChild', to='children.child'),
        ),
        migrations.CreateModel(
            name='ContractChildWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contract_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='contracts.contractchild')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=accounts.tokens.generate_invitation_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.tokens.default_invitation_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='contracts.contract')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('edited', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_originator', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='contracts.contract')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_shares', to='accounts.family')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='families',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractShare', to='accounts.family'),
        ),
        migrations.CreateModel(
            name='ContractTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('net_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('night_presence_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits_in_kind', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('edited', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_terms_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contract terms',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('effective', 'Effective work'), ('presence_responsable', 'Responsible presence'), ('night_presence', 'Night presence')], default='effective', max_length=30)),
                ('is_shared', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('interventions', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_hours', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_hours_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_hours', to='accounts.family')),
            ],
            options={
                'verbose_name_plural': 'exceptional hours',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_presences', to='children.child')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_presences', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_presences_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid leave'), ('unpaid', 'Unpaid leave'), ('sickness', 'Sickness leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('portion', models.CharField(choices=[('full_day', 'Whole day'), ('half_day', 'Half day'), ('hourly', 'Hourly')], default='full_day', max_length=20)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('normal_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hours_25', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hours_50', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits_in_kind_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('kilometers', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('night_count', models.PositiveSmallIntegerField(default=0)),
                ('night_indemnity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('holiday_majoration', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('night_presence_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_periods', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='contracts.contract')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='accounts.family')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='contracts.contractschedule')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractchild',
            constraint=models.UniqueConstraint(fields=('contract', 'child'), name='uniq_contract_child'),
        ),
        migrations.AddConstraint(
            model_name='contractschedule',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_from'), name='uniq_schedule_per_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='contractshare',
            constraint=models.UniqueConstraint(fields=('contract', 'family'), name='uniq_contract_family'),
        ),
        migrations.AddConstraint(
            model_name='contractterms',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_from'), name='uniq_terms_per_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalhours',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), models.Q(('end_date', models.F('start_date')), ('end_time__gt', models.F('start_time'))), _connector='OR'), name='exceptional_hours_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalpresence',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exceptional_presence_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='monthlydeclaration',
            constraint=models.UniqueConstraint(fields=('contract', 'family', 'month'), name='uniq_declaration_per_family_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlydeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='declaration_month_is_first_of_month'),
        ),
    ]
