# Generated by Django 6.0.6 on 2026-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid leave'), ('unpaid', 'Unpaid leave'), ('sickness', 'Sickness leave'), ('maternity', 'Maternity leave')], max_length=20),
        ),
    ]
