# Generated by Django 6.0.6 on 2026-07-22 08:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeclaration',
            name='paid_leave_rappel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
