# Generated by Django 6.0.6 on 2026-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_monthlydeclaration_paid_leave_rappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeclaration',
            name='paid_leave_tenth',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
