# Generated by Django 6.0.6 on 2026-07-22 14:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_monthlydeclaration_paid_leave_tenth'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeclaration',
            name='paid_leave_compensatrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
