# Generated by Django 6.0.6 on 2026-07-03 12:54

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_drop_child_parent'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(unique=True)),
                ('net_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='nanny',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'nannies'},
        ),
        migrations.AddField(
            model_name='nanny',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nannies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nannies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='tracking.nanny')),
            ],
            options={
                'ordering': ['-starting_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=accounts.models.generate_invitation_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_invitation_expiry)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tracking.contract')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tracking.contract')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_originator', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tracking.contract')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_shares', to='accounts.family')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='families',
            field=models.ManyToManyField(related_name='contracts', through='tracking.ContractShare', to='accounts.family'),
        ),
        migrations.CreateModel(
            name='ContractTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('net_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits_in_kind', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tracking.contract')),
            ],
            options={
                'verbose_name_plural': 'contract terms',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tracking.contractschedule')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractschedule',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_from'), name='uniq_schedule_per_effective_date'),
        ),
        migrations.AddConstraint(
            model_name='contractshare',
            constraint=models.UniqueConstraint(fields=('contract', 'family'), name='uniq_contract_family'),
        ),
        migrations.AddConstraint(
            model_name='contractterms',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_from'), name='uniq_terms_per_effective_date'),
        ),
    ]
