# Generated by Django 6.0.6 on 2026-07-05 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('is_workable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
