# Generated by Django 6.0.6 on 2026-07-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_backfill_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanny',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='nanny',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='nanny',
            name='starting_date',
        ),
    ]
