# Generated by Django 6.0.6 on 2026-07-17 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tracking', '0004_bankholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankholiday',
            name='is_solidarity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Equally between the families present'), ('by_children', 'In proportion to the children present')], default='equal', max_length=20),
        ),
        migrations.AddField(
            model_name='contractterms',
            name='night_presence_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='ContractChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_children', to='accounts.child')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_children', to='tracking.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='children',
            field=models.ManyToManyField(related_name='contracts', through='tracking.ContractChild', to='accounts.child'),
        ),
        migrations.CreateModel(
            name='ContractChildWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('contract_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='tracking.contractchild')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('effective', 'Effective work'), ('presence_responsable', 'Responsible presence'), ('night_presence', 'Night presence')], default='effective', max_length=30)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('interventions', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_hours', to='tracking.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_hours_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_hours', to='accounts.family')),
            ],
            options={
                'verbose_name_plural': 'exceptional hours',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_presences', to='accounts.child')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_presences', to='tracking.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_presences_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('normal_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hours_25', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hours_50', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('benefits_in_kind_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('kilometers', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('night_count', models.PositiveSmallIntegerField(default=0)),
                ('night_indemnity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('holiday_majoration', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('night_presence_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mileage_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_periods', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='tracking.contract')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='accounts.family')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractchild',
            constraint=models.UniqueConstraint(fields=('contract', 'child'), name='uniq_contract_child'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalhours',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), models.Q(('end_date', models.F('start_date')), ('end_time__gt', models.F('start_time'))), _connector='OR'), name='exceptional_hours_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='exceptionalpresence',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exceptional_presence_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='monthlydeclaration',
            constraint=models.UniqueConstraint(fields=('contract', 'family', 'month'), name='uniq_declaration_per_family_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlydeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='declaration_month_is_first_of_month'),
        ),
    ]
