# Generated by Django 6.0.6 on 2026-07-17 15:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_bankholiday_is_solidarity_contract_split_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionalhours',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlydeclaration',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
