# Generated by Django 6.0.6 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_drop_nanny_owner_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='paid_leave_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractschedule',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractterms',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
