# Generated by Django 6.0.6 on 2026-07-22 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_seed_minimum_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidLeaveAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(unique=True)),
                ('annual_days', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
