# Generated by Django 6.0.6 on 2026-07-22 08:35

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_seed_paid_leave_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryContributionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(unique=True)),
                ('rate', models.DecimalField(decimal_places=7, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.9999999'))])),
            ],
            options={
                'ordering': ['-effective_from'],
                'abstract': False,
            },
        ),
    ]
